CREATE TABLE "user"
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tg_user_id BIGINT NOT NULL,
    tg_user_access_hash BIGINT,
    settings jsonb NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX user_id_idx ON "user" (id);
CREATE INDEX user_tg_user_id_id ON "user" (tg_user_id);
CREATE INDEX user_settings ON "user" USING gin (settings);