CREATE TABLE "user"
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tg_user_id BIGINT NOT NULL,
    tg_user_access_hash BIGINT,
    settings jsonb NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);